# Generated by Django 4.2.7 on 2023-11-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('Student_ID_number', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Full_name', models.CharField(max_length=50)),
                ('Group_number', models.CharField(max_length=50)),
            ],
        ),
    ]
