# Generated by Django 4.2.3 on 2023-11-02 19:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curators',
            fields=[
                ('Full_name', models.CharField(max_length=50)),
                ('Group_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_number', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('Group_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_subject', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.groups')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('ID_subjects', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Group_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.groups')),
            ],
        ),
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_marks', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('marks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.marks')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='subject_mark',
            field=models.ManyToManyField(through='quest.StudentMarks', to='quest.marks'),
        ),
    ]
