# Generated by Django 4.2.7 on 2023-11-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0002_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Group_number', models.CharField(max_length=50)),
            ],
        ),
    ]
