# Generated by Django 4.2.7 on 2023-11-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0003_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='id',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='Group_number',
        ),
        migrations.AddField(
            model_name='groups',
            name='Group_number',
            field=models.CharField(default=1, max_length=50, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
