# Generated by Django 4.2.7 on 2023-11-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0004_remove_groups_id_remove_groups_group_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curators',
            fields=[
                ('Full_name', models.CharField(max_length=50)),
                ('Group_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RenameField(
            model_name='subjects',
            old_name='name',
            new_name='Name',
        ),
    ]
