# Generated by Django 4.2.7 on 2023-11-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0006_alter_subjects_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='Group_number',
            field=models.CharField(max_length=50),
        ),
    ]
