# Generated by Django 4.2.7 on 2023-11-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0007_alter_subjects_group_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Groups',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
    ]
