# Generated by Django 4.2.7 on 2023-11-02 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0010_remove_groups_id_groups_alter_groups_group_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjects',
            name='Group_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest.groups'),
        ),
    ]
