# Generated by Django 4.2.7 on 2023-11-02 12:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest', '0011_alter_subjects_group_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('ID_mark', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Name_subject', models.CharField(max_length=50)),
                ('Full_name', models.CharField(max_length=50)),
                ('Mark', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
    ]
